name: spot_movie
description: "An app to discover filming locations of movies shot in San Francisco."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_typeahead: ^5.2.0
  geocoding: ^3.0.0
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  logger: ^2.4.0
  permission_handler: ^10.3.0
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true

